services:
  db:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ikated
  redis:
    image: redis:latest
    ports:
      - 6379:6379